version: '3.8'

services:
  frontend:
    build:
      context: ./Juice Planner Frontend/juice-planner-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Juice Planner Backend/juice-planner-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://Benjerry:123benjerrY@cluster-benjerry.rnjjawb.mongodb.net/?retryWrites=true&w=majority&appName=cluster-Benjerry